version: '3.9' # 推荐使用较新的 Compose 文件格式版本

services:
  redis:
    image: redis:7.2-alpine # 推荐使用带版本号且更轻量的 Alpine 镜像
    container_name: deepseek_dispatcher-redis # 为 Redis 容器设置明确的名称
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # 映射具名卷用于 Redis 数据持久化
    restart: always

  dispatcher:
    build: .
    image: deepseek-dispatcher:latest # 明确镜像名称
    container_name: deepseek_dispatcher # 为 Dispatcher 容器设置明确的名称
    ports:
      - "8000:8000" # 映射 FastAPI 端口
    volumes:
      - ./logs:/app/logs # 映射本地的 ./logs 目录到容器的 /app/logs 目录
    environment:
      # Redis URL 会被所有 Supervisor 管理的程序继承，指向 Redis 容器的明确名称
      - REDIS_URL=redis://deepseek_dispatcher-redis:6379/0
      # 大模型 API Key 也在此处设置，会被 Worker 和 FastAPI 继承
      - DASHSCOPE_API_KEY=你的_DashScope_API_Key_放这里 # <<<< 请替换成你的实际 DashScope API Key
      - DEEPSEEK_API_KEY=你的_DeepSeek_API_Key_放这里 # <<<< 请替换成你的实际 DeepSeek API Key
      # ... 其他可能需要的环境变量 ...
    depends_on:
      - redis # 确保 redis 服务在 dispatcher 之前启动
    restart: always

volumes:
  redis_data: {} # 声明一个名为 redis_data 的具名卷，用于 Redis 数据持久化